# Generated by Django 4.2.3 on 2023-11-22 19:23

from django.db import migrations, models
import django.db.models.deletion
import post.models.postImage


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=post.models.postImage.image_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='post.post')),
            ],
            options={
                'verbose_name': 'Post_Image',
                'verbose_name_plural': 'Post_Images',
                'db_table': 'post_image',
            },
        ),
    ]
