# Generated by Django 4.2.3 on 2023-11-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models.postImage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to=post.models.postImage.image_upload_path),
        ),
    ]
