# Generated by Django 4.2.3 on 2023-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='natural_disaster',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='social_disaster',
            field=models.TextField(default=''),
        ),
    ]
