# Generated by Django 4.2.3 on 2023-12-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('onOff', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(null=True)),
                ('roadAdress', models.CharField(null=True)),
                ('zoneCode', models.CharField(null=True)),
                ('xCoordinate', models.CharField(null=True)),
                ('yCoordinate', models.CharField(null=True)),
                ('aliasType', models.CharField(choices=[('home', 'home'), ('school', 'school'), ('work', 'work'), ('etc', 'etc')], null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'region',
            },
        ),
    ]
