# Generated by Django 4.2.3 on 2023-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='roadAdress',
        ),
        migrations.AddField(
            model_name='region',
            name='roadAddress',
            field=models.CharField(null=True),
        ),
    ]
